### ISSUE TITLE
发现有两个问题

### ISSUE THREAD

**Issue by hcnode** [NewbranLTD/git-webhook-ci#8]
第一个：文档写的默认的provider是github，看了源码也确实是github，但是npm上的确实gitlab
第二个：因为第一个问题导致出现异常，在这里输出错误是把incomemessage对象整个都输出了，导致出现(node:29157) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON

```
    res.writeHead(400, { 'content-type': 'application/json' });
    res.end(
      JSON.stringify({
        error: msg
      })
    );
    this.emit('error', new Error(msg));
```

**Comment by joel-chu** [comment]
@hcnode - we have moved everything away from Github since a year ago. You are looking at a very old version here on Github. If you check the npm website, all our code are now on [Gitlab](https://gitlab.com/newbranltd/git-webhook-ci) cheers

**Comment by hcnode** [comment]
@joel-chu ok, but it would be better there is note in the README tell people this project has migrated to gitlab
